### PR TITLE
Fix for CGNS-263

### PR DESCRIPTION
**Pull request by brtnfld**
https://cgnsorg.atlassian.net/browse/CGNS-263

This line

add_library(cgns_f2c OBJECT cgns_f.F90)

was added to address, CGNS-10. @TonyGarratt can you verify this does not break windows builds?

For reference, this was the commit:

https://github.com/CGNS/CGNS/commit/51a3fe82d3fd81302592193b8f45607f3b4dc74e

### CODE REVIEW

**Comment by brtnfld** [comment]
Looks to break builds on macOS.

**Comment by MicK7** [comment]
@brtnfld I changed the fix with a CMAKE Property. Thus the compiler fPIC option will be used when generating the object.

**Comment by brtnfld** [comment]
@MicK7 looks good, thanks. 

I think all we need is to verify there is not an issue on Windows. We are not currently testing CGNS with Fortran on Windows.

**Review by MicK7 — APPROVED** [review]

**Comment by MicK7** [comment]
@TonyGarratt Do you plan to check this change ?

**Comment by brtnfld** [comment]
I'll see if I can get my windows box working to test this.

**Comment by MicK7** [comment]
Maybe we could rely on intel OneAPI new compiler for testing. https://github.com/oneapi-src/oneapi-ci
It looks possible to add it to github CI : https://github.com/oneapi-src/oneapi-ci/blob/master/.github/workflows/build_all.yml

**Comment by brtnfld** [comment]
Looks like it since they have fortran.

**Comment by MicK7** [comment]
I don't think anyone is testing CGNS with fortran on windows recently.

**Comment by MicK7** [comment]
Since the reported issue is on Linux and not windows, I think we should merge this change and create a separated issue for windows (if there is a similar problem).

**Pull request merged**
