### PR TITLE
_stat32i64 is msvc-specific

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by mennodeij** [comment]
It was already inside a #ifdef _WIN32 statement, but I guess that is too general? 
I added the #define stat _stat32i64 to enable the loading of large files on Windows. Make sure to test that for your situation.

**Comment by jschueller** [comment]
yeah, but that's only relevant to the msvc compiler, not for mingw

**Comment by jschueller** [comment]
is it ok to merge ? or ... ?

**Comment by mennodeij** [comment]
As far as I'm concerned yes.

**Comment by jschueller** [comment]
cc @brtnfld

**Pull request merged**
