### PR TITLE
Added HDF5 tuning routine "H5Pset_elink_file_cache_size"

### PR DESCRIPTION
**Pull request by brtnfld**
Helpful when many external links are used.

### CODE REVIEW

**Comment by MicK7** [comment]
Interesting.
Do you have any benchmark that show the improvement?

**Comment by brtnfld** [comment]
It is mainly a workaround for the following issue, which Greg reported and has shown to help.
https://jira.hdfgroup.org/browse/HDFFV-11109

You'll have to register to see the issue:
https://www.hdfgroup.org/community/community-development/

**Comment by MicK7** [comment]
What an issue! It reminds me of some debugging I have done in pyCGNS because external links were not closing properly.

**Comment by brtnfld** [comment]
https://jira.hdfgroup.org/browse/HDFFV-11231

May also be a problem. Currently, CGNS uses just the file object id to find the number of open objects.

**Comment by MicK7** [comment]
> https://jira.hdfgroup.org/browse/HDFFV-11231
> https://jira.hdfgroup.org/browse/HDFFV-11231
> May also be a problem. Currently, CGNS uses just the file object id to find the number of open objects.

**Pull request merged**
