### PR TITLE
CGNS-233 Does configure.ac need to check for zlib/szip headers?

### PR DESCRIPTION
**Pull request by MicK7**
Remove header checking for zlib and szip.

### CODE REVIEW

**Comment by MicK7** [comment]
Regenerating with autoconf the configure file is needed before merging.

**Comment by MicK7** [comment]
@markcmiller86   Thanks for reporting the autotools CGNS issue. Here is a quick hack of the CGNS configure that hopes to be included in next release. Do you think it would be enough for VisIt ?

**Comment by markcmiller86** [comment]
LGTM! Thanks so much!

**Comment by brtnfld** [comment]
can you run Autoconf and commit configure

**Comment by MicK7** [comment]
@brtnfld  Sorry I don't have access to any unix machine right now and will not have access to one next week too.
If you could add the configure I would be thankful.

**Comment by MicK7** [comment]
@brtnfld Thanks so much

**Review by brtnfld — APPROVED** [review]

**Pull request merged**
