### PR TITLE
Modernize CGNS cmake

### PR DESCRIPTION
**Pull request by MicK7**
- use target_link_libraries
- remove close command with clause

https://raw.githubusercontent.com/boostcon/cppnow_presentations_2017/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf

### CODE REVIEW

**Review by brtnfld — COMMENTED** [review]
I'm not an expert on CMake, but the changes look good to me. I'll test the branch in our local CI tests over the next few days.

Have you tested on windows?

**Comment by brtnfld** [comment]
CMake Error at src/CMakeLists.txt:575 (add_library):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:cgns_f2c>

  Objects of target "cgns_f2c" referenced but no such target exists.


CMake Error at src/CMakeLists.txt:575 (add_library):
  No SOURCES given to target: cgns_static

**Comment by MicK7** [comment]
> CMake Error at src/CMakeLists.txt:575 (add_library): Error evaluating generator expression:
> 
> ```
> $<TARGET_OBJECTS:cgns_f2c>
> ```
> 
> Objects of target "cgns_f2c" referenced but no such target exists.
> 
> CMake Error at src/CMakeLists.txt:575 (add_library): No SOURCES given to target: cgns_static

Yes I have seen this issue. Sorry, I messed up with the $.

**Comment by MicK7** [comment]
> I'm not an expert on CMake, but the changes look good. I'll test the branch in our local CI tests over the next few days.
> 
> Have you tested on windows?

I am developing on windows with MSVC (I will switch back to Intel OneAPI after. Hoping to nailed out more easily why fortran wrapping doesn't go well)

**Comment by brtnfld** [comment]
For the parallel tests, it looks like the path to the executables is not correct. For the serial test, the path is, for example, src/tests/test_complexf, but for the parallel tests, it's:

/opt/pkgs/software/MPICH/3.3-GCC-7.2.0-2.29/bin/mpiexec "2" "./pcgns_ctest"

**Comment by MicK7** [comment]
> For the parallel tests, it looks like the path to the executables is not correct. For the serial test, the path is, for example, src/tests/test_complexf, but for the parallel tests, it's looking in the current directory:
> 
> /opt/pkgs/software/MPICH/3.3-GCC-7.2.0-2.29/bin/mpiexec "2" "./pcgns_ctest"
> 
> The cmake command was
> 
> `cmake -D CMAKE_C_COMPILER:PATH=mpicc -D 'CMAKE_C_FLAGS:STRING=-g -fPIC' -D 'CMAKE_Fortran_FLAGS:STRING=-g -fPIC' -D CMAKE_BUILD_TYPE:STRING=Debug -D CMAKE_Fortran_COMPILER:PATH=mpif90 -D CGNS_BUILD_SHARED:BOOL=ON -D CGNS_USE_SHARED:BOOL=ON -D CMAKE_STATIC_LINKER_FLAGS:STRING= -D CGNS_ENABLE_TESTS:BOOL=ON -D CGNS_BUILD_CGNSTOOLS:BOOL=OFF -D CMAKE_INSTALL_PREFIX:PATH=./ -D 'CMAKE_EXE_LINKER_FLAGS:STRING=-Wl,--no-as-needed -ldl' -D CGNS_ENABLE_PARALLEL:BOOL=ON -D HDF5_NEED_MPI:BOOL=ON -D CGNS_ENABLE_LFS:BOOL=OFF -D CGNS_ENABLE_HDF5:BOOL=ON -D CMAKE_PREFIX_PATH=/mnt/scr1/pre-release/hdf5/vdev/jelly-pp-33-g720 -D HDF5_NEED_ZLIB:BOOL=ON -D HDF5_NEED_SZIP:BOOL=ON -D SZIP_LIBRARY:PATH=/mnt/hdf/packages/szip-PIC/static/encoder/Linux2.6-x86_64-gcc/lib/libsz.a -D CGNS_ENABLE_FORTRAN:BOOL=ON -D CGNS_ENABLE_64BIT:BOOL=ON -D CGNS_ENABLE_SCOPING:BOOL=OFF /home/brtnfld/scratch/hdfdts/scripts/external/test.5/CGNS_SRC`

I have made a small modification for the parallel tests.
I am almost happy with the current status of the branch. Just need to remove some commented code to look better...
and test everything.

**Comment by brtnfld** [comment]
I added autotools builds for Test_UserGuideCode/C_code_parallel. Most of the tests fail, so I'm looking into fixing them unless you've already fixed them.

**Comment by brtnfld** [comment]
It is not running tests in  Test_UserGuideCode/C_code_parallel. You will need the code fixes in #318.

**Comment by MicK7** [comment]
> It is not running tests in Test_UserGuideCode/C_code_parallel. You will need the code fixes in #318.

I will add them later after #318 is merged.
The basic goal was to have a more clean and modern CMake base to check why intel oneAPI on windows is buggy.

**Comment by brtnfld** [comment]
Testing last night still fails the parallel tests due to a missing path to the executable. The path now does not have a "./"

**Comment by brtnfld** [comment]
Path is there, but it is missing the "-np" in the exec. command, it does have the number of ranks correct.

**Comment by MicK7** [comment]
> Path is there, but it is missing the "-np" in the exec. command, it does have the number of ranks correct.

There was a copy-paste bug (missing an underscore)

**Comment by brtnfld** [comment]
I still don't get the "-np"

**Comment by brtnfld** [comment]
All tests passed.

**Review by brtnfld — APPROVED** [review]
Passes all regression tests locally.

**Pull request merged**
