### PR TITLE
Rind plane indexing

### PR DESCRIPTION
**Pull request by MicK7**
This pull request improves rind plane indexing for coordinates reading and writing.
pcgnslib is still a work in progress. Refactoring can be improved.

### CODE REVIEW

**Comment by brtnfld** [comment]
Sorry, I'll try to look at the code this week.

**Comment by brtnfld** [comment]
I don't see the documenation for the new cg*_coord_general_* APIs. Do you have a PR for those?

**Comment by smguzik** [comment]
It follows the API in CPEX 40.  I can take care of merging this request if you want.

Stephen

Stephen Guzik, Ph.D.
Assistant Professor, Department of Mechanical Engineering
Colorado State University

On 09/23/2018 03:11 PM, Scot Breitenfeld wrote:

I don't see the documenation for the new cg*coord_general* APIs. Do you have a PR for those?

**Comment by brtnfld** [comment]
That would be great, thanks.

**Comment by brtnfld** [comment]
I thought this was going into develop?

**Comment by MicK7** [comment]
Before going into develop, Fortran mapping of CPEX40 functions may need to be checked or created.
We also need to be confident about test coverage.

As soon as these points are fine, we can merge into develop.

**Comment by brtnfld** [comment]
Are you ok with it going into the next release as we are scheduled to release it very soon?

**Comment by rhbush** [comment]
OK by me…

Bob

**Comment by smguzik** [comment]
Can I have the weekend to look it over?

Stephen Guzik, Ph.D.
Assistant Professor, Department of Mechanical Engineering
Colorado State University

On 10/05/2018 06:36 AM, Scot Breitenfeld wrote:

Are you ok with it going into the next release as we are scheduled to release it very soon?

**Comment by brtnfld** [comment]
Yes, I have a few other issues I'm trying to finish before the 3.3.2 release.

**Comment by MicK7** [comment]
> 
> 
> Are you ok with it going into the next release as we are scheduled to release 3.3.2 very soon?

Would it be possible to name the next release 3.4.0 ? Indeed there are major changes and moreover the new cgns ngon layout rely on Version 3400 to do conversion on the fly (in cgns_internal.c),

**Comment by brtnfld** [comment]
Sure, it will be 3.4.0.

**Comment by brtnfld** [comment]
Stephen,

Have you had a chance to look it over, can I go ahead and merge the PR?

**Pull request merged**
