### PR TITLE
Test to fix CGNS96 PR

### PR DESCRIPTION
**Pull request by MicK7**

### CODE REVIEW

**Comment by brtnfld** [comment]
I would like to merge PR #174 to remove the version number updates from the pull request.

**Comment by brtnfld** [comment]
I wish we had tests for the cgnstools ...

There is also an open issue related to this:
https://cgnsorg.atlassian.net/browse/CGNS-147
But it looks like your changes still work with MPI. I will need a test on OSX. And we need to test cmake, and probably look into PR #14

**Comment by MicK7** [comment]
@brtnfld I agree 😢 
The configure code is a big mess and I just did a quick and dirty fix.
The open issue https://cgnsorg.atlassian.net/browse/CGNS-147 is normal since the mpi detection code is commented in configure script...

**Comment by MicK7** [comment]
I would prefer to improve PR#14

**Comment by brtnfld** [comment]
Yes, which was why it was not merged, but we should address this issue when getting the cgnstools regression tested on other platforms.

**Pull request merged**
