### PR TITLE
ADFH: check for the H5L info structure type directly

### PR DESCRIPTION
**Pull request by mathstuf**
Newer HDF5 builds can still choose to have old ABIs.

### CODE REVIEW

**Review by brtnfld — CHANGES_REQUESTED** [review]
Thanks for noticing this issue.

All the #if H5_VERSION_GE(1,12,0) need to be replaced in the file with:

#if H5_VERSION_GE(1,12,0) && !defined(H5_USE_110_API) && !defined(H5_USE_18_API) && !defined(H5_USE_16_API)

instead of #if defined(H5Lget_info_vers) && H5Lget_info_vers == 2

It works then, for example, when hdf5 1.14 is built with v18 API compatibility.

**Comment by mathstuf** [comment]
Is making a top-level define for this better at the top of the file? `CGNS_HDF5_HAVE_112_API`?

**Comment by brtnfld** [comment]
> Is making a top-level define for this better at the top of the file? `CGNS_HDF5_HAVE_112_API`?

That would be fine as well.

**Review by brtnfld — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
