### PR TITLE
increment version for next release

### PR DESCRIPTION
**Pull request by brtnfld**

### CODE REVIEW

**Comment by MicK7** [comment]
I think we also need to update the VersionList at line 262 of cgnslib.c

**Review by MicK7 — APPROVED** [review]

**Comment by brtnfld** [comment]
fixed

**Comment by brtnfld** [comment]
I missed that in the 4.3.0 release, I should add 4300 and I guess release it again.

**Comment by ArchangeGabriel** [comment]
> I missed that in the 4.3.0 release, I should add 4300 and I guess release it again.

Please avoid re-releasing, it breaks things in distros that had already packaged the new version (Arch Linux for instance AFAIC). Now we have two different tarballs for 4.3.0, our archiving system does not like that… Better release a 4.3.1 that just fix that and move on. ;)

**Comment by ArchangeGabriel** [comment]
Also I recommend creating a release checklist for things like this that should be done at each release, so that you don’t miss any. :)

**Comment by brtnfld** [comment]
You're right, my apologies.

**Pull request merged**
