### PR TITLE
missing offset suffix

### PR DESCRIPTION
**Pull request by MicK7**
@brtnfld This small change fix the issue found by Dave Taflin
It could be backported to 4.1

### CODE REVIEW

**Comment by brtnfld** [comment]
Do you mean release 4.1.2? This fix looks fine; for reference, I summarized the issue in CGNS-219. 
Do you think we should add this file and test for backward compatibility, or is it too specific to this issue?
This might also fix CGNS-214?

**Comment by MicK7** [comment]
Yes I mean a small 4.1.2 release.
I added a commit to also fix CGNS-214.

**Comment by MicK7** [comment]
@brtnfld travis status is not being reported correctly thus the PR can not be merged

**Comment by brtnfld** [comment]
I've disabled Travis until it is running again.

**Pull request merged**
