### PR TITLE
Cmake OpenGL includes

### PR DESCRIPTION
**Pull request by MicK7**
Try to improve OpenGL include detection while not breaking configure

https://cgnsorg.atlassian.net/browse/CGNS-106

### CODE REVIEW

**Comment by brtnfld** [comment]
I'm assuming this does not work on OSX.

**Comment by MicK7** [comment]
Indeed the configure does not work but, for the CMake part, I am not sure if adding
"include_directories(${TCL_INCLUDE_PATH} ${TK_INCLUDE_PATH} ${OPENGL_INCLUDE_DIR})"  in the CMakeLists.txt of tkogl will solve the issue. On OSX, the OPENGL_INCLUDE_SUBDIR should be replaced correctly by the path to OpenGL directory. So I assumed that it may work on OSX but of course should be tested. Is it possible to add this cmake configuration to Travis along existing autotools configuration ?

**Comment by brtnfld** [comment]
Should we make a branch so I can test/resolve mac and windows?

**Comment by MicK7** [comment]
I think so.

**Comment by gsjaardema** [comment]
@MicK7 The fix you suggest above
```adding "include_directories(${TCL_INCLUDE_PATH} ${TK_INCLUDE_PATH} ${OPENGL_INCLUDE_DIR})" in the CMakeLists.txt of tkogl
```
Is the fix suggested in #14 which did seem to fix problem for me on my OSX system in the past.

**Comment by MicK7** [comment]
> 
> 
> @MicK7 The fix you suggest above
> 
> ```
> adding "include_directories(${TCL_INCLUDE_PATH} ${TK_INCLUDE_PATH} ${OPENGL_INCLUDE_DIR})" in the CMakeLists.txt of tkogl
> ```
> 
> Is the fix suggested in #14 which did seem to fix problem for me on my OSX system in the past.

Yes, but I am not sure that it is currently needed with this patch branch since the location of the include headers is generated on the fly by cmake.
Can you try this branch ?

**Comment by brtnfld** [comment]
I created the **build_cgnstools** branch for this work. @MicK7 can you merge your changes to this branch?

**Comment by MicK7** [comment]
@brtnfld ok done

**Pull request closed without merging**
