### PR TITLE
fix compiler issues

### PR DESCRIPTION
**Pull request by MicK7**
Fix compiler issues.
Check C99 Complex support at compile time to enable it.

### CODE REVIEW

**Comment by brtnfld** [comment]
It does not seem to add the necessary flags for the xl compiler. It fixed the issue on Suns, and PGI** 

**I think, I'm having an issue with the HDF5 build.

**Comment by MicK7** [comment]
@brtnfld Can you report the failure message for the xl compiler ?

**Comment by brtnfld** [comment]
/opt/xl/xlf15.1_xlc13.1/xlc -g -g   -I.  -o  lib/cgns_error.o -c cgns_error.c
/opt/xl/xlf15.1_xlc13.1/xlc -g -g   -I.   -o  lib/cgns_internals.o -c cgns_internals.c
"cgns_internals.c", line 5843.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5844.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5863.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5864.11: 1506-025 (S) Operand must be a modifiable lvalue.
make: *** [lib/cgns_internals.o] Error 1
CGNS BUILD #FAILED
/opt/xl/xlf15.1_xlc13.1/xlc -g -g   -I.   -o  lib/cgns_internals.o -c cgns_internals.c
"cgns_internals.c", line 5843.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5844.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5863.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5864.11: 1506-025 (S) Operand must be a modifiable lvalue.
make: *** [lib/cgns_internals.o] Error 1
CGNS INSTALL #FAILED
/opt/xl/xlf15.1_xlc13.1/xlc -g -g   -I.   -o  lib/cgns_internals.o -c cgns_internals.c
"cgns_internals.c", line 5843.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5844.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5863.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5864.11: 1506-025 (S) Operand must be a modifiable lvalue.
make: *** [lib/cgns_internals.o] Error 1
CGNS CMAKE TESTING #FAILED
/opt/xl/xlf15.1_xlc13.1/xlc -g -g   -I.   -o  lib/cgns_internals.o -c cgns_internals.c
"cgns_internals.c", line 5843.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5844.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5863.11: 1506-025 (S) Operand must be a modifiable lvalue.
"cgns_internals.c", line 5864.11: 1506-025 (S) Operand must be a modifiable lvalue.

**Comment by MicK7** [comment]
@brtnfld Thank you for the failure log.
Could you also provide the cmake trace with the last change ?

**Comment by brtnfld** [comment]
Our CGNS daily testing on that machine is failing because the cmake version is to old, let me fix that so it runs correctly tonight.

**Comment by brtnfld** [comment]
For cmake builds:

[  5%] Building C object src/CMakeFiles/cgns_static.dir/cgio_ftoc.c.o
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
/bin/sh: -qlanglvl=extc99: command not found
gmake[2]: *** [src/CMakeFiles/cgns_static.dir/cgns_internals.c.o] Error 127
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [src/CMakeFiles/cgns_static.dir/cgns_error.c.o] Error 127
gmake[2]: *** [src/CMakeFiles/cgns_static.dir/cgns_io.c.o] Error 127
gmake[2]: *** [src/CMakeFiles/cgns_static.dir/adf/ADF_interface.c.o] Error 127
gmake[2]: *** [src/CMakeFiles/cgns_static.dir/adf/ADF_internals.c.o] Error 127/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input fil
e specified. Please use -qhelp for more information.

**Comment by brtnfld** [comment]
[  1%] Building C object src/CMakeFiles/cgns_static.dir/cgns_error.c.o
cd /home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_build/src && /opt/xl/xlf15.1_xlc13.1/xlc  -I/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_build/src -I/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src  -g;-qlanglvl=extc99 -g   -qlanglvl=extc99 -o CMakeFiles/cgns_static.dir/cgns_error.c.o   -c /home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_error.c
/opt/xl/xlc/13.1.0.0/xlC/13.1.0/bin/.orig/xlc: 1501-294 (S) No input file specified. Please use -qhelp for more information.
/bin/sh: -qlanglvl=extc99: command not found

**Comment by MicK7** [comment]
@brtnfld the issue was coming from the semi-colon. I don't know why the compiler options get duplicated but it should not be an issue. It should work properly now.

**Comment by brtnfld** [comment]
-qlanglvl=extc99 does not solve the error:

/opt/xl/xlf15.1_xlc13.1/xlc  -I/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_build/src -I/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src  -g -qlanglvl=extc99 -g -o CMakeFiles/cgns_static.dir/cgns_internals.c.o   -c /home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_internals.c
"/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_internals.c", line 5843.11: 1506-025 (S) Operand must be a modifiable lvalue.
"/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_internals.c", line 5844.11: 1506-025 (S) Operand must be a modifiable lvalue.
"/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_internals.c", line 5863.11: 1506-025 (S) Operand must be a modifiable lvalue.
"/home/brtnfld/scratch/hdfdts/scripts/external/test.1/CGNS_SRC/src/cgns_internals.c", line 5864.11: 1506-025 (S) Operand must be a modifiable lvalue.

**Comment by MicK7** [comment]
On a power9 system with xlc v16.1 I do not reproduce the error.

**Comment by brtnfld** [comment]
@MicK7, 16.1 can compile both develop and Experimental_X4-X8_hdf5, neither need a special flag.

**Comment by brtnfld** [comment]
Error in #if CG_BUILD_COMPLEX_C99_EXT for cmake build with PGI:

pgcc -DH5_BUILT_AS_STATIC_LIB -I/home/brtnfld/scratch/hdfdts/scripts/external/test.3/CGNS_build/src -I/home/brtnfld/scratch/hdfdts/scripts/external/test.3/CGNS_SRC/src -I/mnt/scr1/pre-release/hdf5/vdev/platypus-pgi/include  -g -g -O0   -c99 -o CMakeFiles/cgns_static.dir/cgns_internals.c.o   -c /home/brtnfld/scratch/hdfdts/scripts/external/test.3/CGNS_SRC/src/cgns_internals.c
PGC-S-0226-Syntax error in #if (/home/brtnfld/scratch/hdfdts/scripts/external/test.3/CGNS_SRC/src/cgns_internals.c: 42)
PGC-S-0226-Syntax error in #if (/home/brtnfld/scratch/hdfdts/scripts/external/test.3/CGNS_SRC/src/cgns_internals.c: 5830)

**Pull request merged**
