### PR TITLE
bumped version to 4.1 for next release

### PR DESCRIPTION
**Pull request by brtnfld**

### CODE REVIEW

**Comment by brtnfld** [comment]
This might need to be version 5.0 due to cpex0045

**Comment by MicK7** [comment]
I would rather not include cpex0045 in the next release.
Indeed, it needs more testing to check for bugs and forward compatibility issues.

**Comment by brtnfld** [comment]
I was similarily thinking, as I was hoping to release 4.1 with all the current changes in develop.
What I will suggest is the cpex0045 be added as a branch, for now, so that people can try it out before releasing it officially.

**Comment by MicK7** [comment]
Ok, CPEX0045 can be talked over during next CGNS committee meeting.

**Pull request merged**
