### PR TITLE
JIRA CGNS-194

### PR DESCRIPTION
**Pull request by MicK7**
Test update H5Giterate ...

### CODE REVIEW

**Comment by MicK7** [comment]
It would be nice to also remove H5Gget_objinfo from ADFH.c

**Comment by brtnfld** [comment]
> It would be nice to also remove H5Gget_objinfo from ADFH.c

Yes, I should have also included that because it is needed to run with DAOS. It should also be faster since we only need the basic metadata information.

**Comment by MicK7** [comment]
@brtnfld Do I transfer the changes to a CGNS-194 branch on CGNS/CGNS so you can commit directly into it ?

**Comment by brtnfld** [comment]
That will work.

**Pull request closed without merging**
