### PR TITLE
cgnstypes: avoid defining stat

### PR DESCRIPTION
**Pull request by MicK7**
As suggested by @mathstuf a cgns_stat is defined

### CODE REVIEW

**Review by mathstuf — APPROVED** [review]
Thanks, this looks like it'll work a lot better.

**Comment by mennodeij** [comment]
This puts the burden on the library builder to define `CG_HAVE_STAT64_STRUCT`. I miss it being defined in the CMake or configure scripts. I fear that this will re-introduce problems with large files on windows.

**Comment by mathstuf** [comment]
`src/CMakeLists.txt` does the detection (as does `configure`). So that seems fine to me?

The thing is that the status quo is causing problems on Windows (namely build failures) because `#define stat …` ends up conflicting with Windows headers now doing `struct stat` themselves. This ends up with the system header "redefining" `_stat32i64` because of the ham-handed `#define stat` line. It is always better to make *new* names than to try and masquerade under names that may appear if the headers are ever updated to be conforming to any API spec.

**Comment by mennodeij** [comment]
Ok, my bad, I was only looking at the changed files in this PR commit assuming CG_HAVE_STAT64_STRUCT was a newly introduced variable, but it already existed. 
And I agree with your assessment of ham-handedness, the current approach is better.

**Pull request closed without merging**
